

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_boot?serverTimezone=Asia/Seoul
    username: user_spring_boot
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 488478605178-80ik8ipru8j0nuvkpj0ihjupuif91bli.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile